language: python
python:
    - "2.6"
    - "2.7"
install: pip install pymongo nose name_tools validictory scrapelib jellyfish unicodecsv Django argparse --use-mirrors
script: nosetests
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
        - tneale@sunlightfoundation.com
