language: python
python:
    - "2.7"
install: pip install pymongo nose name_tools validictory scrapelib jellyfish unicodecsv Django pyes argparse pytz --use-mirrors
script: nosetests
services: mongodb
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
        - tneale@sunlightfoundation.com
