language: python
python:
    - "2.7"
services: mongodb
install: pip install pymongo nose name_tools validictory scrapelib jellyfish unicodecsv Django pyes pytz celery boto --use-mirrors
script: nosetests && django-admin.py test api --settings=billy.tests.django_settings --pythonpath=.
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
        - tneale@sunlightfoundation.com
